[package]
name = "libui-vscode-launcher"
version = "0.1.0"
edition = "2024"

[dependencies]
directories = "6.0.0"
libui = "0.4.0"
thiserror = "2.0.12"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
